# 首先定义工作流的名称（可选）
name: Deploy to GitHub Pages

# 然后定义触发事件 (必须放在最顶层)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 接着定义任务
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # Step 1: 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Step 3: 安装依赖
      - name: Install dependencies
        run: npm install --force

      # Step 4: 构建项目
      - name: Generate static files
        run: npm run build

      # Step 5: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          external_repository: djklmin/djklmin.github.io
          keep_files: false
