- name: Deploy to GitHub Pages
  run: |
    cd public
    git init
    git config user.name "GitHub Actions"
    git config user.email "github-actions@github.com"
    git add .
    git commit -m "Deploy: $(date)"
    git push https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/djklmin/djklmin.github.io.git HEAD:main --force

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4  # 从 v3 更新到 v4

    - name: Setup Node.js
      uses: actions/setup-node@v4  # 从 v3 更新到 v4
      with:
        node-version: '20'  # 更新 Node.js 版本
        cache: 'npm'

    - name: Install dependencies
      run: npm install --force

    - name: Generate static files
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # 从 v3 更新到 v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
        publish_branch: main
        external_repository: djklmin/djklmin.github.io
        keep_files: false
